version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10
commands:
  parcel-build:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install && npm rebuild
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}

      - run:
          name: Running lint
          command: yarn lint:ts

      - run:
          name: Running tests
          command: yarn test

      - run:
          name: Running parcel build
          command: yarn build
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./public
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            branches:
              only:
                - master
jobs:
  build:
    executor: node-executor
    environment:
      NETLIFY_SITE_ID: ec2ba6e2-57f6-4810-bc5f-b364b851a158
      NETLIFY_ACCESS_TOKEN: 3d88dddd394725d0f0fadaa3d683a12f5060b4a56f9eb703181083195da797db
    working_directory: ~/project
    steps:
      - parcel-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=dist
  release:
    executor: node-executor
    environment:
      NETLIFY_SITE_ID: ec2ba6e2-57f6-4810-bc5f-b364b851a158
      NETLIFY_ACCESS_TOKEN: 3d88dddd394725d0f0fadaa3d683a12f5060b4a56f9eb703181083195da797db
    working_directory: ~/project
    steps:
      - parcel-build
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist